### ISSUE TITLE
Script testing

### ISSUE THREAD

**Issue by conventi** [facebook/transform#10]
The compiling of ffmpeg source code + the filter plugin requires a lot of time. Is there some method do avoid recompiling the code after every change? In other words, is there a way to recompile only the filter code without having to recompile ffmpeg each time?

**Comment by puffpio** [comment]
Generally building ffmpeg again should only need to recompile changed files and then relink everything together.
Are you seeing that it recompiles every source file over again?

**Comment by conventi** [comment]
You're right! Sorry for the stupid question.
