### ISSUE TITLE
Access to a VR 360 video player+ raw 360 video?

### ISSUE THREAD

**Issue by arianaa30** [facebook/transform#12]
Hi,
Can we get access to an open-sourced 360 video player on Samsung Gear or oculus and add features and whatnot?
Plus, how can we access to a raw 360 video to play with? The 360 jet video can suffice as I thought it might be public. Is there any link to the raw version of the video? https://code.facebook.com/posts/1126354007399553/next-generation-video-encoding-techniques-for-360-video-and-vr/

**Comment by thomasflynn** [comment]
I'd like to echo the request for source for how to playback video in this format.  at least for one viewport.  it would be nice to fully understand how to map the video to the pyramid.  example geometry and associated shaders would be nice.  I assume it would be up to the developer to figure out how many viewports to encode for and when and how to switch between the viewports.

**Comment by puffpio** [comment]
Would recommend checking out this sample 360 player and seeing what it would take to modify to play back alternate projections: https://github.com/fbsamples/360-video-player-for-android
