### ISSUE TITLE
Unable to pass the compiler on mac osx 10.11

### ISSUE THREAD

**Issue by vellow** [facebook/transform#15]
The default ffmpeg source code compile success, when add this filter, screw up everything.
Then I try on debian, compile success, but not work on mac.  

I have install some dependency library tools, and try  `./configure --enable-gpl`, 
Here is the complain.
<img width="643" alt="screen shot 2016-06-16 at 9 47 19 am" src="https://cloud.githubusercontent.com/assets/4065313/16103013/69522a98-33a7-11e6-9564-11c88a5724b2.png">

**Comment by puffpio** [comment]
what version off ffmpeg are you building? the instructions for compiling this project were based off of ffmpeg 2.8

**Comment by vellow** [comment]
Latest version, seems to be ffmpeg 3, I just give  another try on ffmpeg 2.8.7, 2.6.5,  some error. But  debian works fine.

**Comment by puffpio** [comment]
hi @vellow I just tried with a fresh pull of ffmpeg (trunk) and added the transform filter. it built on my macbook pro without issue

anymore debug info you can provide?

**Comment by vellow** [comment]
What a foolish mistake I made... I kept editing on `Makefile` instead of `libavfilter/Makefile`.  Sorry but thanks @puffpio
