### ISSUE TITLE
subdivisions calculation

### ISSUE THREAD

**Issue by dev-rkoshlyak** [facebook/transform#16]
float y = (i + (suby + 0.5f) / s->h_subdivisons) / out_h;
float x = (j + (subx + 0.5f) / s->w_subdivisons) / out_w;
Should it be something like this?
float y = (i + suby / (float) h_subdivisions - 0.5f) / out_h
Because right now we don't look for 0.5 around instead we look at 1 aside and 0.5f is not clear what doing at all.

**Comment by evgenykuzyakov** [comment]
The idea here is to iterate through sub-pixels of each pixel. We divide each pixel into sub-pixels (e.g. 4x4). So for the top-left pixel from (0.0, 0.0) to (1.0, 1.0) we have top-left sub-pixel from (0.0, 0.0) to (0.25, 0.25). Its center is at (0.125, 0.125). The next sub-pixel on the right has the center at (0.375, 0.125). Here is how it's computed:

    (subx + 0.5f) / s->w_subdivisons

    for subx = 0: (0 + 0.5) / 4 = 0.125
    for subx = 1: (1 + 0.5) / 4 = 0.375

So now to calculate global sub-pixel offset we just need to add left and top offset of the pixel itself.
I hope it helps.
