### ISSUE TITLE
why the cubemap video is very fuzzy？

### ISSUE THREAD

**Issue by NankaiZBP** [facebook/transform#17]
I converted a video using command “ ffmpeg -i input.mp4 -vf transform='input_stereo_format=MONO:w_subdivisons=4:h_subdivisons=4:max_cube_edge_length=512' output.mp4 ”.
The original video size is 82MB with a resolution ratio of 1920*960。The output video size is only 17MB with a resolution ratio of 1440 * 960. The compression ratio is too high, so the output video is very fuzzy.  How can I change the command option to make the output video more clear?

**Comment by puffpio** [comment]
Check out @boblaublaw's answer in #13 
The command line you provided does the cubemap transform, but you will need to learn about using ffmpeg for video compression as well (which is out of scope of this project)

**Comment by NankaiZBP** [comment]
thanks
