### ISSUE TITLE
Is there any reference papers on the algorithm?

### ISSUE THREAD

**Issue by bobonovski** [facebook/transform#19]
Hello, guys,
Is there any reference papers on the algorithm? A link?

**Comment by puffpio** [comment]
Here are two high level articles on the subject:
https://code.facebook.com/posts/1638767863078802/under-the-hood-building-360-video/
https://code.facebook.com/posts/1126354007399553/next-generation-video-encoding-techniques-for-360-video-and-vr/

And here is a video which explains things in more detail
https://www.youtube.com/watch?v=zpuUUxMfaJs

Hope that helps get you pointed in the right direction
