### ISSUE TITLE
border of six squares

### ISSUE THREAD

**Issue by miraclestar** [facebook/transform#2]
I converted a 4k video using this tool.
I found that every square has about 1 pix border which will split the video when playing.

see the pic below :
![image](https://cloud.githubusercontent.com/assets/1502697/12710524/8a6e2666-c8f2-11e5-9fa7-86f8c1b8a245.png)

**Comment by puffpio** [comment]
You can control this border with the expand_coef parameter. The default is 1.01 (1%) border. Without a small border you will get some artifacts at the cube boundaries when you wrap it on the cube polygon. By adding a small border, you can then texture the cube with the region within the boundaries and avoid the artifacts

**Comment by miraclestar** [comment]
thank you @puffpio :+1:
