### ISSUE TITLE
Found a unity Player which implemented this algorithm

### ISSUE THREAD

**Issue by miraclestar** [facebook/transform#20]
“The first player which can play cubic VR videos in unity ! 】 ;”

[https://www.assetstore.unity3d.com/en/#!/content/62143](
https://www.assetstore.unity3d.com/en/#!/content/62143)

**Comment by evgenykuzyakov** [comment]
Another Unity player that supports cubemap projection is AVPro:
https://www.assetstore.unity3d.com/en/#!/content/56355
