### ISSUE TITLE
Forum for developer discussions?

### ISSUE THREAD

**Issue by boblaublaw** [facebook/transform#8]
To my knowledge, there is no community or forum to discuss the transform project.  I am hopeful that Facebook would turn on the "gitter" chat capability for this repository, but barring that, would suggest that interested people convene on the "#360" channel of the "vrdev" slack team.

Slack doesn't allow for public joins, so if you are interested please request an invite here:  https://t.co/tltfdGvqXf

**Comment by puffpio** [comment]
Thanks for shoutout to that channel :)
There's also the 360 community on FB here that we monitor: https://www.facebook.com/groups/facebook360community/
